Running on desktop18:
stdin: is not a tty
Activating chexpert environment...
Traceback (most recent call last):
  File "bin/test_model.py", line 150, in <module>
    main()
  File "bin/test_model.py", line 147, in main
    run(args)
  File "bin/test_model.py", line 113, in run
    ckpt = torch.load(ckpt_path, map_location=device)
  File "/home/katkr/.conda/envs/chexpert/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/katkr/.conda/envs/chexpert/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/katkr/.conda/envs/chexpert/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/katkr/Shortcuts-Problem-in-Medical-Image-Analysis/shortcuts-chest-xray/logdirs/logdir-30k-2/Best_Balanced_Sex_2_01.ckpt'
