Running on desktop22:
stdin: is not a tty
Activating chexpert environment...
Traceback (most recent call last):
  File "bin/test_model.py", line 153, in <module>
    main()
  File "bin/test_model.py", line 150, in main
    run(args)
  File "bin/test_model.py", line 128, in run
    y_score, y_pred, sensitive_y_score, sensitive_y_pred = test_epoch(cfg, args, model, dataloader_test)
  File "bin/test_model.py", line 76, in test_epoch
    print("from test_epoch output:", output.shape)
AttributeError: 'list' object has no attribute 'shape'
